{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-protocol",
    "version": "1.20.1+build.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.18.jar",
          "url": "raincoat-protocol-1.20.1+build.18.jar",
          "size": 4311,
          "sha512": "78eb84638d1e62276d4e23655e52a3f6c212838f1b76a5fd1994c441cfaf18a7b3ec347ba69b90070ebe898f2c34daeec5d9835e07cb6a7c4f85a40fd13123fb",
          "sha256": "7b1c29753bc457143d784d8591b26199f81020f311744783d76246b50335f72d",
          "sha1": "f2ea24737788ef305c9752ea95d390b23d49ac5a",
          "md5": "29f7e111e4f9f490da690d6b26dab26b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.18.jar",
          "url": "raincoat-protocol-1.20.1+build.18.jar",
          "size": 4311,
          "sha512": "78eb84638d1e62276d4e23655e52a3f6c212838f1b76a5fd1994c441cfaf18a7b3ec347ba69b90070ebe898f2c34daeec5d9835e07cb6a7c4f85a40fd13123fb",
          "sha256": "7b1c29753bc457143d784d8591b26199f81020f311744783d76246b50335f72d",
          "sha1": "f2ea24737788ef305c9752ea95d390b23d49ac5a",
          "md5": "29f7e111e4f9f490da690d6b26dab26b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.18-javadoc.jar",
          "url": "raincoat-protocol-1.20.1+build.18-javadoc.jar",
          "size": 101225,
          "sha512": "860139de8ea26be3caf4aa5801e24c1fcd1c08c8dbc814e6c58cd063720b1e77612d76fd1d2cc908e4baea1748bc531ca86db0a42276b2e3d164bd106290209c",
          "sha256": "1b2b86004f4e2e1543002f46aa3e9d3cb58c0b7410479b81693309c4dce56deb",
          "sha1": "a0f91fd04d4846fd8ce5c0326ead1f8ffb29d7c8",
          "md5": "01455a0cb857bee4959452ca674345ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.18-sources.jar",
          "url": "raincoat-protocol-1.20.1+build.18-sources.jar",
          "size": 2144,
          "sha512": "d862ad3a98cf3846baabb62169256871892b9554110e968b345a48c83466babc92cbaac6d3bb88e7171a14a657fa2e9a4f931de8211e88930247d0884dad90e2",
          "sha256": "6ea922b77ed68f4f880b8b9aa5dbb5b5d86dfa1b5a340f4a12f4596aa1d115e4",
          "sha1": "326ebb366d006affdd0a1154f0fbb1d28a78735f",
          "md5": "7a854f5b61c0efe657aa215953388990"
        }
      ]
    }
  ]
}
