{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "main+build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "main+build.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-main+build.1.jar",
          "url": "raincoat-fabric-main+build.1.jar",
          "size": 78881,
          "sha512": "dc9ee1de80a42f9c08c5f988e9af421f9ad39a579db3be71670377cc333ae7625b29605454485eaedacee03b4ef3ce1fcaab36b3a7b7b21f4ca59cb3369cce5d",
          "sha256": "63b84f6c1f4132892e543f1cdf7377e44cc52b0b7e1dcaa527bf60509e3e28d3",
          "sha1": "adf0ede64fce7e7ef5c9a5c52c774a10ec416b3c",
          "md5": "c4494d0337000ecd6e2a8cac190a7049"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "main+build.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.13+0d0f210290"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.9+93d8cb8290"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.2.2+9244241690"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.29+9244241690"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.8.2+574a764890"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.23+aaaf9d3390"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.8+3b1d070f90"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-main+build.1.jar",
          "url": "raincoat-fabric-main+build.1.jar",
          "size": 78881,
          "sha512": "dc9ee1de80a42f9c08c5f988e9af421f9ad39a579db3be71670377cc333ae7625b29605454485eaedacee03b4ef3ce1fcaab36b3a7b7b21f4ca59cb3369cce5d",
          "sha256": "63b84f6c1f4132892e543f1cdf7377e44cc52b0b7e1dcaa527bf60509e3e28d3",
          "sha1": "adf0ede64fce7e7ef5c9a5c52c774a10ec416b3c",
          "md5": "c4494d0337000ecd6e2a8cac190a7049"
        }
      ]
    }
  ]
}
