{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-protocol",
    "version": "1.20.1+build.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.5.jar",
          "url": "raincoat-protocol-1.20.1+build.5.jar",
          "size": 4281,
          "sha512": "59e744228097e69b072a59e3798d5a9ea97e30641af2fe9f931921fa6a6d023ceaa6f74736dc2d41ce29f788b2247395a16c03d29c40c3697771f3a7c22c29c8",
          "sha256": "1f4e4f3533aa8ddddf7b2721073db65e62789369517223f27832aa58118a572a",
          "sha1": "ef881f9589307c1f4957763eac0f528100259127",
          "md5": "66f42db1aa497955e2ff3b3a228dccfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.5.jar",
          "url": "raincoat-protocol-1.20.1+build.5.jar",
          "size": 4281,
          "sha512": "59e744228097e69b072a59e3798d5a9ea97e30641af2fe9f931921fa6a6d023ceaa6f74736dc2d41ce29f788b2247395a16c03d29c40c3697771f3a7c22c29c8",
          "sha256": "1f4e4f3533aa8ddddf7b2721073db65e62789369517223f27832aa58118a572a",
          "sha1": "ef881f9589307c1f4957763eac0f528100259127",
          "md5": "66f42db1aa497955e2ff3b3a228dccfc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.5-javadoc.jar",
          "url": "raincoat-protocol-1.20.1+build.5-javadoc.jar",
          "size": 101149,
          "sha512": "9a111d49a0551bfeafe216c7a26f9e9135cd55500ec30d30f2bb4356ba08b9be9dc39b4ee164ff7fb51802927aa82fa8e3de9f15b6ccbc0693825344c15a4b44",
          "sha256": "c3d8d6f731f4395af4d34b35c44554503152a413d2865a58277ab946a9ac2ac5",
          "sha1": "782a8e07d51e921eae7753272cfe0d4796ee474a",
          "md5": "cd34c9bf6b4721c590e01cbaacc49ab8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.5-sources.jar",
          "url": "raincoat-protocol-1.20.1+build.5-sources.jar",
          "size": 2130,
          "sha512": "7ed593564b2145c2a546ca2e866b92505dddd679db7aad4137e60b8c7a94e519de60e4219811737c4720ae4d76655296e62ea7ba3757c016794dfce42f29c6f7",
          "sha256": "9c6f7e1aeba586e5321110d1f2ae8dfb339971d719d0044a458efa02130d07f8",
          "sha1": "4f356079b70ee953b77f5084d935e2b9b95a7c7c",
          "md5": "8807dd92a9f161a45530c861edf9dd89"
        }
      ]
    }
  ]
}
