{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rainbootsmc",
    "module": "mcef-fabric",
    "version": "2.1.4-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1.jar",
          "url": "mcef-fabric-2.1.4-1.20.1.jar",
          "size": 224262,
          "sha512": "5b68370de057996a9fec21a98d4be209c58cb484fd3dfab64594947086390cdd455ea73ed46b83f06ff2782097dec5def4ce73418e229a7b43eef9e9b237f083",
          "sha256": "6f5da0ce6a7e85e41db3e64346b836c41e90162ef4f35eea1b144748dc9ddead",
          "sha1": "436f4bc408300384dead8f282e21507fe110e2e5",
          "md5": "168d36d804d304f9bdd4a2e9a98522de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.rainbootsmc",
          "module": "mcef",
          "version": {
            "requires": "2.1.4-1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.29+b04edc7a82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.11+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.2.20+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.3.8+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.7+f7923f6d82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.36+fb8d95da82"
          }
        }
      ],
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1.jar",
          "url": "mcef-fabric-2.1.4-1.20.1.jar",
          "size": 224262,
          "sha512": "5b68370de057996a9fec21a98d4be209c58cb484fd3dfab64594947086390cdd455ea73ed46b83f06ff2782097dec5def4ce73418e229a7b43eef9e9b237f083",
          "sha256": "6f5da0ce6a7e85e41db3e64346b836c41e90162ef4f35eea1b144748dc9ddead",
          "sha1": "436f4bc408300384dead8f282e21507fe110e2e5",
          "md5": "168d36d804d304f9bdd4a2e9a98522de"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1-shadow-dev.jar",
          "url": "mcef-fabric-2.1.4-1.20.1-shadow-dev.jar",
          "size": 212843,
          "sha512": "244e7765bcfc45397a3c23f7c859d89cbb82a02afa1e2fb879450cd64ed39c63830adeb4e8f990502fbe5bdd4b429b3ec58d53b67828f7973d28510f4dddbe07",
          "sha256": "4650042a36b8281937c95126040fcc44bc8dfe07aade484bf9f89e6244ebafa6",
          "sha1": "bc4531b77b9729409c644f8cb8a023ec19e7a25a",
          "md5": "11f60f80f2d697bb1d42d26a926be19d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1-sources.jar",
          "url": "mcef-fabric-2.1.4-1.20.1-sources.jar",
          "size": 4430,
          "sha512": "28aa04ad1a997d3d2bd641be206158030e0c7d5b29357532639f996e2a0b76847d6d7b9d6b85a1431132c33e7172cc30750c8d51dc514765918a6b818bbe8115",
          "sha256": "b4dafaf875897cbe2199cd999693c21068675194c6720cc819c600e4b16d0f62",
          "sha1": "c4b2e8dd6ee39720b56eaa95b4418ab1f146570f",
          "md5": "c231664c15b1a967dc196e7b9c57d41e"
        }
      ]
    }
  ]
}
