{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rainbootsmc",
    "module": "mcef-fabric",
    "version": "2.1.4-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1.jar",
          "url": "mcef-fabric-2.1.4-1.20.1.jar",
          "size": 224262,
          "sha512": "1e5e0e383d81a5e03ebd507f13972cf4ca7cf217fc81b1bdcfce570b24aca37c1b290b142db7c25e3d7bf870c14834346855f178228fbd2a70c2f68081c3c91d",
          "sha256": "49900df6b5ecd95e85ba88f5167e34d626b73a056520c1fb3a2705b801d85b6d",
          "sha1": "5e3ea24f8d5d1c4d26398faec8a89744a7663392",
          "md5": "b8d08ecb1c6d64426c7c577e47c6fac0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cinemamod",
          "module": "mcef",
          "version": {
            "requires": "2.1.4-1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.29+b04edc7a82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.11+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.2.20+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.3.8+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.7+f7923f6d82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.36+fb8d95da82"
          }
        }
      ],
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1.jar",
          "url": "mcef-fabric-2.1.4-1.20.1.jar",
          "size": 224262,
          "sha512": "1e5e0e383d81a5e03ebd507f13972cf4ca7cf217fc81b1bdcfce570b24aca37c1b290b142db7c25e3d7bf870c14834346855f178228fbd2a70c2f68081c3c91d",
          "sha256": "49900df6b5ecd95e85ba88f5167e34d626b73a056520c1fb3a2705b801d85b6d",
          "sha1": "5e3ea24f8d5d1c4d26398faec8a89744a7663392",
          "md5": "b8d08ecb1c6d64426c7c577e47c6fac0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1-shadow-dev.jar",
          "url": "mcef-fabric-2.1.4-1.20.1-shadow-dev.jar",
          "size": 212842,
          "sha512": "07f5f9d0b0095b996c82f7ed1101649597bb060f53a0567c21a4ec75320831439d58dbe3ecf4f5abe0e6a80697fa4f4586d6661acbef667a658f8e92b3b9cb88",
          "sha256": "877fc8c7a47d2d57e0b09899c820914999a950776a0c60a3c34939d8eac88ada",
          "sha1": "8bdef4a29437056e7e398a7b4dadbdd7089f4e99",
          "md5": "c6643dfef0b43999cd22b9a70373ff19"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.4-1.20.1-sources.jar",
          "url": "mcef-fabric-2.1.4-1.20.1-sources.jar",
          "size": 4430,
          "sha512": "36a94ad8782dccb9086aa1df1de0848ee414eef32c866541a6a84309ea3185bcfb037cb5efcde47e2b79fdd91a9dd6aff1d1ac63ef19ce5e027ec41904ea6395",
          "sha256": "fff4890607ae71be60dcbd7c62ab934dd1fa4c9f12efbb4e3c01a5632febe45c",
          "sha1": "a48371a8864b3695865972982d1c03908ceb91a0",
          "md5": "9bc58cd6b0363834a9ffa46002577ebd"
        }
      ]
    }
  ]
}
