{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "1.20.1+build.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.29"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.29.jar",
          "url": "raincoat-fabric-1.20.1+build.29.jar",
          "size": 4522383,
          "sha512": "172678a52cb6ab878a6612bd0bc5ce668781aa5861634fbcf66eb20ffe8a4aa710324093d8220c4f7319c36c50c334bc61f405b3fd28e8624cca3f912477b34d",
          "sha256": "777202252c67508d0870cb6d7102ad33f9aa6904d9aa96b3df16495d5b961bae",
          "sha1": "5af5028f693886bc6b8352c20e898f377f2915bd",
          "md5": "25b95f8ee413dfc0fc442f69bd588350"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel-coroutines",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.29"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result-jvm",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.29.jar",
          "url": "raincoat-fabric-1.20.1+build.29.jar",
          "size": 4522383,
          "sha512": "172678a52cb6ab878a6612bd0bc5ce668781aa5861634fbcf66eb20ffe8a4aa710324093d8220c4f7319c36c50c334bc61f405b3fd28e8624cca3f912477b34d",
          "sha256": "777202252c67508d0870cb6d7102ad33f9aa6904d9aa96b3df16495d5b961bae",
          "sha1": "5af5028f693886bc6b8352c20e898f377f2915bd",
          "md5": "25b95f8ee413dfc0fc442f69bd588350"
        }
      ]
    }
  ]
}
