{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "1.20.1+build.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.19"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.19.jar",
          "url": "raincoat-fabric-1.20.1+build.19.jar",
          "size": 4464052,
          "sha512": "938869a8d6f6d9cdc81076dcd1339f12ff3a2f01dd33a00a8690cf88b9c94111d7e30a1100f25fb4337ca64e1ad38429f62cf4d4f3dc138e6cf033bfefd97c8b",
          "sha256": "d8a0f842d982501726f65a3403d69ab40bcf8eccfc94a27ac9721667493780eb",
          "sha1": "1c35e150ba27a6c82c781fdcc46955ea1d603df5",
          "md5": "45be36c5c1b2456f5b3a16fafd6ed9e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel-coroutines",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.19"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result-jvm",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.19.jar",
          "url": "raincoat-fabric-1.20.1+build.19.jar",
          "size": 4464052,
          "sha512": "938869a8d6f6d9cdc81076dcd1339f12ff3a2f01dd33a00a8690cf88b9c94111d7e30a1100f25fb4337ca64e1ad38429f62cf4d4f3dc138e6cf033bfefd97c8b",
          "sha256": "d8a0f842d982501726f65a3403d69ab40bcf8eccfc94a27ac9721667493780eb",
          "sha1": "1c35e150ba27a6c82c781fdcc46955ea1d603df5",
          "md5": "45be36c5c1b2456f5b3a16fafd6ed9e2"
        }
      ]
    }
  ]
}
