{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "1.20.1+build.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.16"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.16.jar",
          "url": "raincoat-fabric-1.20.1+build.16.jar",
          "size": 4464440,
          "sha512": "fe990dcfe97b65be0a8895a6549cc480dda44df65f111e6a04bb98dd26e6932e9e9710b1ae5e9c0d6e0816bb403c1434cb1a4d376d6969c271e9220ce53d6137",
          "sha256": "ed79a23f6c8a0d74a15804e0ba6967f6bfca8f5af8ea140da641d035baaf33c2",
          "sha1": "46f9239cfcf35d5ee50487d49dcbc4694df84cf1",
          "md5": "55f01ab12b6f776038cb9e21d94b1155"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel-coroutines",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.16"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result-jvm",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.16.jar",
          "url": "raincoat-fabric-1.20.1+build.16.jar",
          "size": 4464440,
          "sha512": "fe990dcfe97b65be0a8895a6549cc480dda44df65f111e6a04bb98dd26e6932e9e9710b1ae5e9c0d6e0816bb403c1434cb1a4d376d6969c271e9220ce53d6137",
          "sha256": "ed79a23f6c8a0d74a15804e0ba6967f6bfca8f5af8ea140da641d035baaf33c2",
          "sha1": "46f9239cfcf35d5ee50487d49dcbc4694df84cf1",
          "md5": "55f01ab12b6f776038cb9e21d94b1155"
        }
      ]
    }
  ]
}
