{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "1.19.4+build.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.19.4+build.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "6.1.0-rc.4"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.19.4+build.7.jar",
          "url": "raincoat-fabric-1.19.4+build.7.jar",
          "size": 4283230,
          "sha512": "e67351aa5c6673ec1f0fab4eae38a8d26e69c44d8f607427fdfda205c5055f8ae91eff3cbf34c72c2601c72d56592e8b21516d5e188835dd729b2ec4678d2f00",
          "sha256": "954094415ac82351f37465c80e4fcbe31cedad5381dfcbf306232eb7bb1cc760",
          "sha1": "7f6206880363e33151d8f8c5141ccd1dcc55d343",
          "md5": "b43882926184afac35d9663615730ec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel-coroutines",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.19.4+build.7"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result-jvm",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "6.1.0-rc.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.19.4+build.7.jar",
          "url": "raincoat-fabric-1.19.4+build.7.jar",
          "size": 4283230,
          "sha512": "e67351aa5c6673ec1f0fab4eae38a8d26e69c44d8f607427fdfda205c5055f8ae91eff3cbf34c72c2601c72d56592e8b21516d5e188835dd729b2ec4678d2f00",
          "sha256": "954094415ac82351f37465c80e4fcbe31cedad5381dfcbf306232eb7bb1cc760",
          "sha1": "7f6206880363e33151d8f8c5141ccd1dcc55d343",
          "md5": "b43882926184afac35d9663615730ec8"
        }
      ]
    }
  ]
}
