{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "1.20.1+build.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.30"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.30.jar",
          "url": "raincoat-fabric-1.20.1+build.30.jar",
          "size": 4524729,
          "sha512": "3e2f320b139c83e0242a739ac583052d18b7a5cf0a5a426db4cf3be81b819b22ee8e6e40213aa5671d22ace298ca337ea78bac6a25f8956c7a4a31a0619535b1",
          "sha256": "eee428aa87ca4b7db19b3b3a025fccdabff582b9b8cc5c82fc816867274657e7",
          "sha1": "10197b39bc6947187c893abb95f9fd1dc8b3d13c",
          "md5": "7f0177bdfb48df905c1cb6783b1b539f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel-coroutines",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.20.1+build.30"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result-jvm",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.20.1+build.30.jar",
          "url": "raincoat-fabric-1.20.1+build.30.jar",
          "size": 4524729,
          "sha512": "3e2f320b139c83e0242a739ac583052d18b7a5cf0a5a426db4cf3be81b819b22ee8e6e40213aa5671d22ace298ca337ea78bac6a25f8956c7a4a31a0619535b1",
          "sha256": "eee428aa87ca4b7db19b3b3a025fccdabff582b9b8cc5c82fc816867274657e7",
          "sha1": "10197b39bc6947187c893abb95f9fd1dc8b3d13c",
          "md5": "7f0177bdfb48df905c1cb6783b1b539f"
        }
      ]
    }
  ]
}
