{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-protocol",
    "version": "1.20.1+build.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.24.jar",
          "url": "raincoat-protocol-1.20.1+build.24.jar",
          "size": 4410,
          "sha512": "bd307c4035abf841be71c8d61a54a9d72a1493b4c097afe282c4e50881e8c2f3ae3d6c5c63e636c3a0c5411963740dd9c4dbedb6b51ee0ac093bcd3fd9044997",
          "sha256": "b82f4f1c2fe65865bcc178643338b6c38527f6e776eb3ca3dd3481c79192f6f6",
          "sha1": "bcf30dab5deff8f2d3cd2e0b63563f3242930e0a",
          "md5": "8a69c2ab95cb561ec8f1e20655db1afc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.24.jar",
          "url": "raincoat-protocol-1.20.1+build.24.jar",
          "size": 4410,
          "sha512": "bd307c4035abf841be71c8d61a54a9d72a1493b4c097afe282c4e50881e8c2f3ae3d6c5c63e636c3a0c5411963740dd9c4dbedb6b51ee0ac093bcd3fd9044997",
          "sha256": "b82f4f1c2fe65865bcc178643338b6c38527f6e776eb3ca3dd3481c79192f6f6",
          "sha1": "bcf30dab5deff8f2d3cd2e0b63563f3242930e0a",
          "md5": "8a69c2ab95cb561ec8f1e20655db1afc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.24-javadoc.jar",
          "url": "raincoat-protocol-1.20.1+build.24-javadoc.jar",
          "size": 101395,
          "sha512": "841ba830e0b393f68c409be16404f2da329e445ca5e7e36e2c4f2a6762fbfabab5f3119d1600959dd905c53bfee083cd69488e308cf06d0b469ca7408ad510b3",
          "sha256": "7b303302184f65dc28745e46517f3295956a0222dd45edafbf9ae5be24a80396",
          "sha1": "01122252945a2898837ad734dad931048a69920d",
          "md5": "29fd7530302eb406d174d0692e03abac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.24-sources.jar",
          "url": "raincoat-protocol-1.20.1+build.24-sources.jar",
          "size": 2190,
          "sha512": "f8c7e4569dac01b4dcfb91c63b2d459130897976aa4775bc14c1112f0cc46a9e0f69e0a301ec4411c519fae0547b7247d9267375d294777a34022357a56903e0",
          "sha256": "1e5585f0adf533f2a5fb139220ef260571ae8fa820cf8fd8dc117ca5a6ecbd04",
          "sha1": "ad3d35bce060c28b8a1b7485a460defd0d9b5e04",
          "md5": "1ec8b074cd2c1a5386e0a4c6155173e6"
        }
      ]
    }
  ]
}
