{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "1.19.2+build.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.19.2+build.5"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.19.2+build.5.jar",
          "url": "raincoat-fabric-1.19.2+build.5.jar",
          "size": 81156,
          "sha512": "0b1e6689e8d16bfbd40865c754f66eab01186d2e2518164b1accc26f4e9813df6b02dcf78d038180b94292abce6dfab534e8e5cd1dd56104166d77f3199a334c",
          "sha256": "6d33f73423a630f29f78ec3bc4cf5b9c1799f6f9b2a170922cff09bfc9e58f56",
          "sha1": "d7a6a199eafc9b87472b1c074724f9e739c3d355",
          "md5": "168bcdc6b8c30f4f0c72fa2866798752"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.19.2+build.5"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.13+0d0f210290"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.9+93d8cb8290"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.2.2+9244241690"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.29+9244241690"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.8.2+574a764890"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.23+aaaf9d3390"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.8+3b1d070f90"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.19.2+build.5.jar",
          "url": "raincoat-fabric-1.19.2+build.5.jar",
          "size": 81156,
          "sha512": "0b1e6689e8d16bfbd40865c754f66eab01186d2e2518164b1accc26f4e9813df6b02dcf78d038180b94292abce6dfab534e8e5cd1dd56104166d77f3199a334c",
          "sha256": "6d33f73423a630f29f78ec3bc4cf5b9c1799f6f9b2a170922cff09bfc9e58f56",
          "sha1": "d7a6a199eafc9b87472b1c074724f9e739c3d355",
          "md5": "168bcdc6b8c30f4f0c72fa2866798752"
        }
      ]
    }
  ]
}
