{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-protocol",
    "version": "1.20.1+build.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.27.jar",
          "url": "raincoat-protocol-1.20.1+build.27.jar",
          "size": 4451,
          "sha512": "59463b62b7783aed8bdd1113348eaceaec49eadda918b816605316961e4b5b264b07b0cf9254cf25e283fb4cb26367a4d2d266bdc4410caea319fb644b9ff5dc",
          "sha256": "c1a247642b9ed7ec6b61d9a36467134d87917ba842fb60c681993cf12b8f5098",
          "sha1": "87a462f8741c4f6de6a813b40eb1db37e81ac6e9",
          "md5": "abbbbbeef6071dcbd76ed9ee1d439a8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.27.jar",
          "url": "raincoat-protocol-1.20.1+build.27.jar",
          "size": 4451,
          "sha512": "59463b62b7783aed8bdd1113348eaceaec49eadda918b816605316961e4b5b264b07b0cf9254cf25e283fb4cb26367a4d2d266bdc4410caea319fb644b9ff5dc",
          "sha256": "c1a247642b9ed7ec6b61d9a36467134d87917ba842fb60c681993cf12b8f5098",
          "sha1": "87a462f8741c4f6de6a813b40eb1db37e81ac6e9",
          "md5": "abbbbbeef6071dcbd76ed9ee1d439a8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.27-javadoc.jar",
          "url": "raincoat-protocol-1.20.1+build.27-javadoc.jar",
          "size": 101474,
          "sha512": "59061ac14211905f43d32a6b191ce772c5485f724751f4423383c051f274254432b0d20f2ec78158d5e68a718d623bc0b8b1da781aa9be73fa58e6ca566dbb5e",
          "sha256": "6edb851748bddcb1e57eb6e62131405107c37f1906934501c5850336212d6f13",
          "sha1": "4a310adae3f66f5180364faf018ca80948c50494",
          "md5": "c57ab02acc8f48308a5d6d1f8f64eacb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "raincoat-protocol-1.20.1+build.27-sources.jar",
          "url": "raincoat-protocol-1.20.1+build.27-sources.jar",
          "size": 2206,
          "sha512": "339d11f3421b4246ddbe83cce76e6d46193e13fedf9ca723dbbdddad92b60d55657ce21b94e131d6778c8c9f3be7f42ed04439e9b12d47414f0d1c836f8f71c7",
          "sha256": "7877b15b8b81f2c97585ebe94bf61a6ed1c3550dfbbdaa1589deba91d595fc54",
          "sha1": "bf875886543209ac9fda274d2bf7bfa53b6690b7",
          "md5": "9b5a5c88d82c871bc1dd0d6c3a328da3"
        }
      ]
    }
  ]
}
