{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rainbootsmc",
    "module": "mcef-fabric",
    "version": "2.1.5-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1.jar",
          "url": "mcef-fabric-2.1.5-1.20.1.jar",
          "size": 224264,
          "sha512": "d744070482ac6152c734c89ca71456598f9959576ed09f5332224f7d0b952d19ef9074f9a5b3e17de59097d8be5dfc9b46ba4931e67bf397d8f97108aa46b318",
          "sha256": "5fc434efda5a62cb1318b16c325844777348775891a0b7e8cbbd83a0d521b39b",
          "sha1": "33e513de524b7d2ba8b5612b7decf9330560cbc4",
          "md5": "944e5d065d83c399f6fafb58fe515dbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.rainbootsmc",
          "module": "mcef",
          "version": {
            "requires": "2.1.5-1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.29+b04edc7a82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.11+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.2.20+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.3.8+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.7+f7923f6d82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.36+fb8d95da82"
          }
        }
      ],
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1.jar",
          "url": "mcef-fabric-2.1.5-1.20.1.jar",
          "size": 224264,
          "sha512": "d744070482ac6152c734c89ca71456598f9959576ed09f5332224f7d0b952d19ef9074f9a5b3e17de59097d8be5dfc9b46ba4931e67bf397d8f97108aa46b318",
          "sha256": "5fc434efda5a62cb1318b16c325844777348775891a0b7e8cbbd83a0d521b39b",
          "sha1": "33e513de524b7d2ba8b5612b7decf9330560cbc4",
          "md5": "944e5d065d83c399f6fafb58fe515dbd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1-shadow-dev.jar",
          "url": "mcef-fabric-2.1.5-1.20.1-shadow-dev.jar",
          "size": 212848,
          "sha512": "ed02e89b7f5e576236e71cc88ee0953cfffa29aa4e9f4d26fad009eca00fa8a82b65e1403b11c6e30d94c389fd747133fccc628d095b050eb9b46bf63caf299c",
          "sha256": "b26b5cc8b8611b53718fffdc75510e572b82a8b3e811c26ade5ac32b58349cac",
          "sha1": "44eceadff7ebce7f86acee8481c74f7cab3479d6",
          "md5": "ee16a1602bc0e6fc564fef209c5cc8fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1-sources.jar",
          "url": "mcef-fabric-2.1.5-1.20.1-sources.jar",
          "size": 4430,
          "sha512": "8b14ab74af88f6ddeb42a9e6387119dae740f040a060f1d769b8d1f2223d395fbe46c8fb2fe5e68f3db66f8b752cb9e160ad5a671d678ffcc61b1d73fa22cf16",
          "sha256": "fde69946bc8d7f4f3efe6621f1bf922483afefad924206413f07f631fc0cffaa",
          "sha1": "f28458cbcfcbf5b162833eaef475405f92ddd1fd",
          "md5": "e1791dac747cd07e6355a27489b48a75"
        }
      ]
    }
  ]
}
