{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rainbootsmc",
    "module": "mcef-fabric",
    "version": "2.1.5-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1.jar",
          "url": "mcef-fabric-2.1.5-1.20.1.jar",
          "size": 224293,
          "sha512": "cb4c62486c47129bf6654e7bbde3d0d452f8c0819f1490e334cce0b9f9b92d7de37b256940d2243fde5af593fd09e8b97aa5a84b2cc9fb06294dde48a13ba2ce",
          "sha256": "09b72273b59375e0121f5b4f2962479e901a1ab8c0e858b2928c7f5ec0c875b4",
          "sha1": "83a54f50be5f7ed9e8961d1d2a56f092ed7b09b5",
          "md5": "7ee063ed377629dbe063089fc1073050"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.rainbootsmc",
          "module": "mcef",
          "version": {
            "requires": "2.1.5-1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.29+b04edc7a82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.11+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.2.20+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.3.8+b3afc78b82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.7+f7923f6d82"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.36+fb8d95da82"
          }
        }
      ],
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1.jar",
          "url": "mcef-fabric-2.1.5-1.20.1.jar",
          "size": 224293,
          "sha512": "cb4c62486c47129bf6654e7bbde3d0d452f8c0819f1490e334cce0b9f9b92d7de37b256940d2243fde5af593fd09e8b97aa5a84b2cc9fb06294dde48a13ba2ce",
          "sha256": "09b72273b59375e0121f5b4f2962479e901a1ab8c0e858b2928c7f5ec0c875b4",
          "sha1": "83a54f50be5f7ed9e8961d1d2a56f092ed7b09b5",
          "md5": "7ee063ed377629dbe063089fc1073050"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1-shadow-dev.jar",
          "url": "mcef-fabric-2.1.5-1.20.1-shadow-dev.jar",
          "size": 212877,
          "sha512": "49ed7eaab15371ab50122a7320e5a38ed10ef3e1dc94b05f40c96a2c94de9f9de70306ed9fb52c03b64e9d982cbca7416bdf0fb75caa5fea135e86ba8145c7ef",
          "sha256": "5154de00fd4c6e0a02c98d64c1e90766de81157d8489518994473cf0d22375ac",
          "sha1": "96541f70e9f2bb97f0b5f3082c02724afc322bbf",
          "md5": "4fc94428b3675d9c5e318a32ccbe266a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.5-1.20.1-sources.jar",
          "url": "mcef-fabric-2.1.5-1.20.1-sources.jar",
          "size": 4430,
          "sha512": "a3fbc089f7494d5a97887f8ccae7ccb26b008edd2a494e4cc70f1b947c2573981592832a0c192c348446a4f063c13b6b5907be5e7dcb4bcfdd9592c07023247d",
          "sha256": "42cac7dcec025791c596bce766eba8641b0d024072626d66cad179c05c2dc9e5",
          "sha1": "63b33b30e40bf2694e775f75a85f44b36b479ca7",
          "md5": "5c6e24888560786fe06628e17c4da5c1"
        }
      ]
    }
  ]
}
