{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "raincoat-fabric",
    "version": "1.19.2+build.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.19.2+build.4"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.19.2+build.4.jar",
          "url": "raincoat-fabric-1.19.2+build.4.jar",
          "size": 80152,
          "sha512": "491440b7353f6c46343fcfba4893ab209407b2b79bebb9335157f0870f90ac33ad0978b1e0fd3793bcc5e638f4ba45e8e76e79d735adcbd5bc7dce41afa21c7e",
          "sha256": "71f55c9ae30d13425b68c94eb7532072c82fc6f58a37143281e4e9e5827fee03",
          "sha1": "2f252ba2e17edb9a9988a983e5d112cd799345b5",
          "md5": "8fd25655740ab976d5895038b2bf1481"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.uten2c",
          "module": "raincoat-protocol",
          "version": {
            "requires": "1.19.2+build.4"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.13+0d0f210290"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.9+93d8cb8290"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.2.2+9244241690"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.29+9244241690"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.8.2+574a764890"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.23+aaaf9d3390"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.8+3b1d070f90"
          }
        }
      ],
      "files": [
        {
          "name": "raincoat-fabric-1.19.2+build.4.jar",
          "url": "raincoat-fabric-1.19.2+build.4.jar",
          "size": 80152,
          "sha512": "491440b7353f6c46343fcfba4893ab209407b2b79bebb9335157f0870f90ac33ad0978b1e0fd3793bcc5e638f4ba45e8e76e79d735adcbd5bc7dce41afa21c7e",
          "sha256": "71f55c9ae30d13425b68c94eb7532072c82fc6f58a37143281e4e9e5827fee03",
          "sha1": "2f252ba2e17edb9a9988a983e5d112cd799345b5",
          "md5": "8fd25655740ab976d5895038b2bf1481"
        }
      ]
    }
  ]
}
